# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bro/Documents/nilbro/viterbi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bro/Documents/nilbro/viterbi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bro/Documents/nilbro/viterbi/CMakeFiles /home/bro/Documents/nilbro/viterbi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bro/Documents/nilbro/viterbi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Viterbi

# Build rule for target.
Viterbi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Viterbi
.PHONY : Viterbi

# fast build rule for target.
Viterbi/fast:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/build
.PHONY : Viterbi/fast

ViterbiEncoder.o: ViterbiEncoder.cpp.o

.PHONY : ViterbiEncoder.o

# target to build an object file
ViterbiEncoder.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/ViterbiEncoder.cpp.o
.PHONY : ViterbiEncoder.cpp.o

ViterbiEncoder.i: ViterbiEncoder.cpp.i

.PHONY : ViterbiEncoder.i

# target to preprocess a source file
ViterbiEncoder.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/ViterbiEncoder.cpp.i
.PHONY : ViterbiEncoder.cpp.i

ViterbiEncoder.s: ViterbiEncoder.cpp.s

.PHONY : ViterbiEncoder.s

# target to generate assembly for a file
ViterbiEncoder.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/ViterbiEncoder.cpp.s
.PHONY : ViterbiEncoder.cpp.s

driver.o: driver.cpp.o

.PHONY : driver.o

# target to build an object file
driver.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/driver.cpp.o
.PHONY : driver.cpp.o

driver.i: driver.cpp.i

.PHONY : driver.i

# target to preprocess a source file
driver.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/driver.cpp.i
.PHONY : driver.cpp.i

driver.s: driver.cpp.s

.PHONY : driver.s

# target to generate assembly for a file
driver.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/driver.cpp.s
.PHONY : driver.cpp.s

monitor.o: monitor.cpp.o

.PHONY : monitor.o

# target to build an object file
monitor.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/monitor.cpp.o
.PHONY : monitor.cpp.o

monitor.i: monitor.cpp.i

.PHONY : monitor.i

# target to preprocess a source file
monitor.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/monitor.cpp.i
.PHONY : monitor.cpp.i

monitor.s: monitor.cpp.s

.PHONY : monitor.s

# target to generate assembly for a file
monitor.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/monitor.cpp.s
.PHONY : monitor.cpp.s

testbench.o: testbench.cpp.o

.PHONY : testbench.o

# target to build an object file
testbench.cpp.o:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/testbench.cpp.o
.PHONY : testbench.cpp.o

testbench.i: testbench.cpp.i

.PHONY : testbench.i

# target to preprocess a source file
testbench.cpp.i:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/testbench.cpp.i
.PHONY : testbench.cpp.i

testbench.s: testbench.cpp.s

.PHONY : testbench.s

# target to generate assembly for a file
testbench.cpp.s:
	$(MAKE) -f CMakeFiles/Viterbi.dir/build.make CMakeFiles/Viterbi.dir/testbench.cpp.s
.PHONY : testbench.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Viterbi"
	@echo "... edit_cache"
	@echo "... ViterbiEncoder.o"
	@echo "... ViterbiEncoder.i"
	@echo "... ViterbiEncoder.s"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... monitor.o"
	@echo "... monitor.i"
	@echo "... monitor.s"
	@echo "... testbench.o"
	@echo "... testbench.i"
	@echo "... testbench.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

